[deps]
GAMS = "1ca51c6a-1b4d-4546-9ae1-53e0a243ab12"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
SquareModels = "8f61fe60-8cc6-11ec-3043-2171a73045bd"

[sources]
# MartinBonde/gams.jl includes a GDX API extension missing from the official repository
GAMS = {url = "https://github.com/MartinBonde/gams.jl"}
SquareModels = {url = "https://github.com/MartinBonde/SquareModels"}

[compat]
julia = "1.12"
